return {
  ["enable"] = true,
  ["ar_prefs"] = {
    ["face_count"] = 0,
    ["suit_ratio_decimal"] = 0,
    ["suit_ratio_id"] = 1,
    ["suit_ratio_percent"] = "Disabled",
    ["use_cuda"] = true,
    ["spf_int"] = 100000,
    ["spf_id"] = 7,
  },
  ["ar_filters"] = {
    ["inst_perkeo"] = false,
    ["tag2_name"] = "",
    ["joker_name"] = "",
    ["joker_id"] = 1,
    ["joker_location_id"] = 1,
    ["tag2_id"] = 1,
    ["voucher_id"] = 1,
    ["inst_observatory"] = false,
    ["tag_id"] = 1,
    ["soul_skip"] = 0,
    ["joker_location"] = "any",
    ["voucher_name"] = "",
    ["pack_id"] = 1,
    ["joker_search"] = "",
    ["tag_name"] = "",
    ["pack"] = {},
  },
  ["keybinds"] = {
    ["save_state"] = "z",
    ["f_reroll"] = "r",
    ["modifier"] = "lctrl",
    ["load_state"] = "x",
    ["options"] = "t",
    ["a_reroll"] = "a",
  },
}
