[manifest]
version = "3.5"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
name = 'nativefs'
source = 'nativefs.lua'
before = 'main.lua'

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["Brainstorm.lua"]

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self:load_profile(G.SETTINGS.profile or 1)"
position = "after"
payload = "Brainstorm.init()"
match_indent = true
overwrite = false
