--- STEAMODDED HEADER
--- MOD_NAME: Brainstorm Supercharged
--- MOD_ID: Brainstorm
--- PREFIX: brainstorm
--- MOD_AUTHOR: [OceanRamen, KRVH]
--- MOD_DESCRIPTION: Brainstorm Supercharged, the Balatro Reroll Mod. Full rewrite by KRVH. Originals: Brainstorm by OceanRamen; Immolate by MathIsFun0.
--- VERSION: 3.5
