--- STEAMODDED HEADER
--- MOD_NAME: Brainstorm
--- MOD_ID: Brainstorm
--- PREFIX: brainstorm
--- MOD_AUTHOR: [OceanRamen, KRVH]
--- MOD_DESCRIPTION: The Balatro Reroll Mod. Original by OceanRamen. Rewrite by KRVH. Immolate by MathIsFun0.
--- VERSION: 3.1
