--- STEAMODDED HEADER
--- MOD_NAME: Brainstorm
--- MOD_ID: Brainstorm
--- PREFIX: brainstorm
--- MOD_AUTHOR: [OceanRamen, KRVH]
--- MOD_DESCRIPTION: The Balatro Reroll Mod. Full rewrite by KRVH. Originals: Brainstorm by OceanRamen; Immolate by MathIsFun0.
--- VERSION: 3.4
