#![allow(clippy::missing_errors_doc)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BenchGroup {
    Baseline,
    Tags,
    Vouchers,
    Packs,
    Jokers,
    Souls,
    Deck,
    Ux,
}

impl BenchGroup {
    pub const fn key(self) -> &'static str {
        match self {
            Self::Baseline => "baseline",
            Self::Tags => "tags",
            Self::Vouchers => "vouchers",
            Self::Packs => "packs",
            Self::Jokers => "jokers",
            Self::Souls => "souls",
            Self::Deck => "deck",
            Self::Ux => "ux",
        }
    }

    pub const fn label(self) -> &'static str {
        match self {
            Self::Baseline => "baseline",
            Self::Tags => "tags",
            Self::Vouchers => "vouchers",
            Self::Packs => "packs",
            Self::Jokers => "jokers",
            Self::Souls => "souls",
            Self::Deck => "deck",
            Self::Ux => "ux",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BenchShape {
    Hit,
    Miss,
    Mixed,
    Static,
}

impl BenchShape {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Hit => "hit",
            Self::Miss => "miss",
            Self::Mixed => "mixed",
            Self::Static => "static",
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct BenchCase {
    pub name: &'static str,
    pub group: BenchGroup,
    pub shape: BenchShape,
    pub note: &'static str,
    pub seed_start: &'static str,
    pub voucher: &'static str,
    pub pack: &'static str,
    pub tag1: &'static str,
    pub tag2: &'static str,
    pub joker: &'static str,
    pub joker_location: &'static str,
    pub souls: f64,
    pub observatory: bool,
    pub perkeo: bool,
    pub deck: &'static str,
    pub erratic: bool,
    pub no_faces: bool,
    pub min_face_cards: i32,
    pub suit_ratio: f64,
}

pub fn selected_bench_cases(selected: &str) -> Result<Vec<BenchCase>, String> {
    let mut cases = bench_cases();
    if selected == "all" {
        return Ok(cases);
    }

    cases.retain(|case| case.name == selected || case.group.key() == selected);
    if cases.is_empty() {
        Err(format!(
            "unknown benchmark case or group: {selected}. Use all, {}, or an exact case name.",
            bench_group_keys().join(", ")
        ))
    } else {
        Ok(cases)
    }
}

pub fn bench_group_keys() -> Vec<&'static str> {
    vec![
        BenchGroup::Baseline.key(),
        BenchGroup::Tags.key(),
        BenchGroup::Vouchers.key(),
        BenchGroup::Packs.key(),
        BenchGroup::Jokers.key(),
        BenchGroup::Souls.key(),
        BenchGroup::Deck.key(),
        BenchGroup::Ux.key(),
    ]
}

pub fn bench_cases() -> Vec<BenchCase> {
    vec![
        BenchCase {
            name: "baseline-hit",
            group: BenchGroup::Baseline,
            shape: BenchShape::Hit,
            note: "no filters from a non-empty seed; isolates ABI/result overhead",
            seed_start: "1",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "tag-hit",
            group: BenchGroup::Tags,
            shape: BenchShape::Hit,
            note: "single blind tag check with early hit behavior",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "dual-tag",
            group: BenchGroup::Tags,
            shape: BenchShape::Static,
            note: "ante-1 locked Buffoon tag; validates zero-work rejection",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "tag_buffoon",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "voucher-hit",
            group: BenchGroup::Vouchers,
            shape: BenchShape::Hit,
            note: "ante-1 voucher roll",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "pack-hit",
            group: BenchGroup::Packs,
            shape: BenchShape::Hit,
            note: "two shop pack slots, pack-only filter",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "observatory",
            group: BenchGroup::Packs,
            shape: BenchShape::Mixed,
            note: "voucher plus celestial pack rolls",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: true,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "shop-hit",
            group: BenchGroup::Jokers,
            shape: BenchShape::Hit,
            note: "first-shop joker slots with a normal joker target",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "shop-miss",
            group: BenchGroup::Jokers,
            shape: BenchShape::Static,
            note: "shop Joker search for legendary Perkeo; validates zero-work rejection",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Perkeo",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "pack-joker",
            group: BenchGroup::Jokers,
            shape: BenchShape::Mixed,
            note: "Buffoon pack slots plus pack joker generation",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Reserved Parking",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "any-joker",
            group: BenchGroup::Jokers,
            shape: BenchShape::Mixed,
            note: "shop-or-pack joker search with a Buffoon pack filter",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Blueprint",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "pack-miss",
            group: BenchGroup::Souls,
            shape: BenchShape::Static,
            note: "Soul count above the first-shop maximum; validates zero-work rejection",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_normal_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 3.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "souls-arcana",
            group: BenchGroup::Souls,
            shape: BenchShape::Mixed,
            note: "Arcana pack Soul counting path",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "perkeo",
            group: BenchGroup::Souls,
            shape: BenchShape::Mixed,
            note: "Soul detection followed by legendary pool roll",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "erratic",
            group: BenchGroup::Deck,
            shape: BenchShape::Mixed,
            note: "Erratic Deck opening-card face count",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 12,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "erratic-suit",
            group: BenchGroup::Deck,
            shape: BenchShape::Mixed,
            note: "Erratic Deck suit concentration check",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.8,
        },
        BenchCase {
            name: "ux-tag-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable single tag filter",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-dual-tag",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable two-tag filter",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "tag_d_six",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-voucher-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable ante-1 voucher filter",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-pack-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable shop pack filter",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-shop-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable shop joker search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-pack-joker-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Buffoon pack joker search",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Reserved Parking",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-mega-buffoon-pack-wee-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Mega Buffoon pack-only Wee Joker long-tail search",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Wee Joker",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-any-joker-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable shop-or-pack joker search",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Blueprint",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-mega-spectral-any-baseball-card",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Mega Spectral plus any-location Baseball Card long-tail search",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "Baseball Card",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-pack-joker-no-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Buffoon joker search without an exact pack filter",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Blueprint",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-normal-buffoon-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable forced normal Buffoon pack Joker search",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_normal_1",
            tag1: "",
            tag2: "",
            joker: "Reserved Parking",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-any-joker-no-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable shop-or-pack joker search without an exact pack filter",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Blueprint",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-arcana-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul Arcana pack search",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-arcana-normal",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul normal Arcana pack search",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_normal_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-normal-arcana-soul-half-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable normal Arcana Soul plus shop Half Joker long-tail search",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_normal_1",
            tag1: "",
            tag2: "",
            joker: "Half Joker",
            joker_location: "shop",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-jumbo-arcana-soul-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Jumbo Arcana Soul plus shop Joker long-tail search",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_jumbo_1",
            tag1: "",
            tag2: "",
            joker: "Joker",
            joker_location: "shop",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-spectral-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul Spectral pack search",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-spectral-normal",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul normal Spectral pack search",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_normal_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-perkeo-arcana",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul Arcana pack plus Perkeo search",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-perkeo-spectral",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul Spectral pack plus Perkeo search",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-perkeo-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable instant Perkeo search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-perkeo-arcana-normal",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable normal Arcana pack plus instant Perkeo search",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_normal_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-observatory-only",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Observatory instant-search toggle",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: true,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-erratic-faces",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Erratic Deck face-count search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 12,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-erratic-suit-50",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable guaranteed Erratic Deck 50% suit-ratio search",
            seed_start: "1",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.5,
        },
        BenchCase {
            name: "ux-erratic-no-faces-suit-50",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable no-face Erratic Deck 50% suit-ratio search",
            seed_start: "1",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: true,
            min_face_cards: 0,
            suit_ratio: 0.5,
        },
        BenchCase {
            name: "ux-erratic-suit-75",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Erratic Deck 75% suit-ratio search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.75,
        },
        BenchCase {
            name: "ux-erratic-suit-85",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Erratic Deck 85% suit-ratio search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.85,
        },
        BenchCase {
            name: "ux-erratic-no-faces-suit",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Erratic Deck suit-ratio search with no-face filtering",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: true,
            min_face_cards: 0,
            suit_ratio: 0.75,
        },
        BenchCase {
            name: "ux-erratic-no-faces-suit-85",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable high-selectivity no-face Erratic Deck suit-ratio search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: true,
            min_face_cards: 0,
            suit_ratio: 0.85,
        },
        BenchCase {
            name: "ux-tag-voucher",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable tag plus voucher search",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-voucher-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable voucher plus pack search",
            seed_start: "",
            voucher: "v_telescope",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-shop-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable tag plus shop joker search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-voucher-shop-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable voucher plus shop joker search",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-erratic-faces",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable tag plus Erratic Deck face-count search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 12,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-voucher-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Miss,
            note: "UI-reachable tag+voucher+pack combination; full-budget UX throughput",
            seed_start: "",
            voucher: "v_telescope",
            pack: "p_spectral_mega_1",
            tag1: "tag_charm",
            tag2: "tag_d_six",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-pack-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Miss,
            note: "UI-reachable tag plus Buffoon pack joker search",
            seed_start: "",
            voucher: "",
            pack: "p_buffoon_mega_1",
            tag1: "tag_charm",
            tag2: "",
            joker: "Blueprint",
            joker_location: "pack",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-voucher-any-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Miss,
            note: "UI-reachable voucher plus shop-or-pack joker search",
            seed_start: "",
            voucher: "v_telescope",
            pack: "p_buffoon_mega_1",
            tag1: "",
            tag2: "",
            joker: "Blueprint",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-soul-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable tag plus one-Soul Arcana pack early-hit latency",
            seed_start: "",
            voucher: "",
            pack: "p_arcana_mega_1",
            tag1: "tag_d_six",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-observatory",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable tag plus Observatory instant-search early-hit latency",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: true,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-same-rare-tag-observatory",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable same Rare Tag twice plus Observatory long-tail latency",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_rare",
            tag2: "tag_rare",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: true,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-erratic-tag-suit",
            group: BenchGroup::Ux,
            shape: BenchShape::Miss,
            note: "UI-reachable Erratic Deck suit ratio plus tag search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.8,
        },
        BenchCase {
            name: "ux-same-tag-twice",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable same-tag-twice search requiring both blind slots",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "tag_charm",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-forced-normal-buffoon",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable forced first-shop normal Buffoon pack",
            seed_start: "1",
            voucher: "",
            pack: "p_buffoon_normal_1",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-soul-no-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable one-Soul search without a selected pack family",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-voucher-soul-no-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Telescope plus one-Soul search without a selected pack",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-voucher-perkeo-no-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Telescope plus Perkeo search without a selected pack",
            seed_start: "",
            voucher: "v_telescope",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-tag-soul-no-pack",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable tag plus one-Soul search without a selected pack family",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 1.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-nonbuffoon-shop-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable non-Buffoon pack plus shop-only Joker search",
            seed_start: "",
            voucher: "",
            pack: "p_spectral_mega_1",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-observatory-perkeo-static",
            group: BenchGroup::Ux,
            shape: BenchShape::Static,
            note: "UI-reachable Observatory plus Perkeo zero-work rejection",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: true,
            perkeo: true,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-erratic-face-suit",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Erratic Deck face-count plus suit-ratio search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 12,
            suit_ratio: 0.75,
        },
        BenchCase {
            name: "ux-erratic-face-35-suit-85",
            group: BenchGroup::Ux,
            shape: BenchShape::Miss,
            note: "UI-reachable high-selectivity Erratic Deck face-count plus suit-ratio search",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 35,
            suit_ratio: 0.85,
        },
        BenchCase {
            name: "ux-erratic-face-35",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable Erratic Deck maximum face-count threshold",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_erratic",
            erratic: true,
            no_faces: false,
            min_face_cards: 35,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-zodiac-shop-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable Zodiac Deck shop Joker search with altered shop rates",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_zodiac",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-ghost-shop-joker",
            group: BenchGroup::Ux,
            shape: BenchShape::Hit,
            note: "UI-reachable Ghost Deck shop Joker search with Spectral shop weight",
            seed_start: "",
            voucher: "",
            pack: "",
            tag1: "",
            tag2: "",
            joker: "Burnt Joker",
            joker_location: "shop",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_ghost",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
        BenchCase {
            name: "ux-random-seed-tag-voucher",
            group: BenchGroup::Ux,
            shape: BenchShape::Mixed,
            note: "UI-reachable composite search from a fixed random-shaped eight-character seed",
            seed_start: "A7K9P3Q2",
            voucher: "v_telescope",
            pack: "",
            tag1: "tag_charm",
            tag2: "",
            joker: "",
            joker_location: "any",
            souls: 0.0,
            observatory: false,
            perkeo: false,
            deck: "b_red",
            erratic: false,
            no_faces: false,
            min_face_cards: 0,
            suit_ratio: 0.0,
        },
    ]
}
