// Generated mechanically from the Immolate item table. Do not reorder entries by hand.
#![allow(non_camel_case_types)]
#![allow(clippy::match_same_arms)]

#[repr(usize)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum Item {
    RETRY = 0,
    J_BEGIN = 1,
    J_C_BEGIN = 2,
    Joker = 3,
    Greedy_Joker = 4,
    Lusty_Joker = 5,
    Wrathful_Joker = 6,
    Gluttonous_Joker = 7,
    Jolly_Joker = 8,
    Zany_Joker = 9,
    Mad_Joker = 10,
    Crazy_Joker = 11,
    Droll_Joker = 12,
    Sly_Joker = 13,
    Wily_Joker = 14,
    Clever_Joker = 15,
    Devious_Joker = 16,
    Crafty_Joker = 17,
    Half_Joker = 18,
    Credit_Card = 19,
    Banner = 20,
    Mystic_Summit = 21,
    _8_Ball = 22,
    Misprint = 23,
    Raised_Fist = 24,
    Chaos_the_Clown = 25,
    Scary_Face = 26,
    Abstract_Joker = 27,
    Delayed_Gratification = 28,
    Gros_Michel = 29,
    Even_Steven = 30,
    Odd_Todd = 31,
    Scholar = 32,
    Business_Card = 33,
    Supernova = 34,
    Ride_the_Bus = 35,
    Egg = 36,
    Runner = 37,
    Ice_Cream = 38,
    Splash = 39,
    Blue_Joker = 40,
    Faceless_Joker = 41,
    Green_Joker = 42,
    Superposition = 43,
    To_Do_List = 44,
    Cavendish = 45,
    Red_Card = 46,
    Square_Joker = 47,
    Riff_raff = 48,
    Photograph = 49,
    Reserved_Parking = 50,
    Mail_In_Rebate = 51,
    Hallucination = 52,
    Fortune_Teller = 53,
    Juggler = 54,
    Drunkard = 55,
    Golden_Joker = 56,
    Popcorn = 57,
    Walkie_Talkie = 58,
    Smiley_Face = 59,
    Golden_Ticket = 60,
    Swashbuckler = 61,
    Hanging_Chad = 62,
    Shoot_the_Moon = 63,
    J_C_END = 64,
    J_U_BEGIN = 65,
    Joker_Stencil = 66,
    Four_Fingers = 67,
    Mime = 68,
    Ceremonial_Dagger = 69,
    Marble_Joker = 70,
    Loyalty_Card = 71,
    Dusk = 72,
    Fibonacci = 73,
    Steel_Joker = 74,
    Hack = 75,
    Pareidolia = 76,
    Space_Joker = 77,
    Burglar = 78,
    Blackboard = 79,
    Sixth_Sense = 80,
    Constellation = 81,
    Hiker = 82,
    Card_Sharp = 83,
    Madness = 84,
    Seance = 85,
    Shortcut = 86,
    Hologram = 87,
    Cloud_9 = 88,
    Rocket = 89,
    Midas_Mask = 90,
    Luchador = 91,
    Gift_Card = 92,
    Turtle_Bean = 93,
    Erosion = 94,
    To_the_Moon = 95,
    Stone_Joker = 96,
    Lucky_Cat = 97,
    Bull = 98,
    Diet_Cola = 99,
    Trading_Card = 100,
    Flash_Card = 101,
    Spare_Trousers = 102,
    Ramen = 103,
    Seltzer = 104,
    Castle = 105,
    Mr_Bones = 106,
    Acrobat = 107,
    Sock_and_Buskin = 108,
    Troubadour = 109,
    Certificate = 110,
    Smeared_Joker = 111,
    Throwback = 112,
    Rough_Gem = 113,
    Bloodstone = 114,
    Arrowhead = 115,
    Onyx_Agate = 116,
    Glass_Joker = 117,
    Showman = 118,
    Flower_Pot = 119,
    Merry_Andy = 120,
    Oops_All_6s = 121,
    The_Idol = 122,
    Seeing_Double = 123,
    Matador = 124,
    Stuntman = 125,
    Satellite = 126,
    Cartomancer = 127,
    Astronomer = 128,
    Bootstraps = 129,
    J_U_END = 130,
    J_R_BEGIN = 131,
    DNA = 132,
    Vampire = 133,
    Vagabond = 134,
    Baron = 135,
    Obelisk = 136,
    Baseball_Card = 137,
    Ancient_Joker = 138,
    Campfire = 139,
    Blueprint = 140,
    Wee_Joker = 141,
    Hit_the_Road = 142,
    The_Duo = 143,
    The_Trio = 144,
    The_Family = 145,
    The_Order = 146,
    The_Tribe = 147,
    Invisible_Joker = 148,
    Brainstorm = 149,
    Drivers_License = 150,
    Burnt_Joker = 151,
    J_R_END = 152,
    J_L_BEGIN = 153,
    Canio = 154,
    Triboulet = 155,
    Yorick = 156,
    Chicot = 157,
    Perkeo = 158,
    J_L_END = 159,
    J_END = 160,
    V_BEGIN = 161,
    Overstock = 162,
    Overstock_Plus = 163,
    Clearance_Sale = 164,
    Liquidation = 165,
    Hone = 166,
    Glow_Up = 167,
    Reroll_Surplus = 168,
    Reroll_Glut = 169,
    Crystal_Ball = 170,
    Omen_Globe = 171,
    Telescope = 172,
    Observatory = 173,
    Grabber = 174,
    Nacho_Tong = 175,
    Wasteful = 176,
    Recyclomancy = 177,
    Tarot_Merchant = 178,
    Tarot_Tycoon = 179,
    Planet_Merchant = 180,
    Planet_Tycoon = 181,
    Seed_Money = 182,
    Money_Tree = 183,
    Blank = 184,
    Antimatter = 185,
    Magic_Trick = 186,
    Illusion = 187,
    Hieroglyph = 188,
    Petroglyph = 189,
    Directors_Cut = 190,
    Retcon = 191,
    Paint_Brush = 192,
    Palette = 193,
    V_END = 194,
    T_BEGIN = 195,
    The_Fool = 196,
    The_Magician = 197,
    The_High_Priestess = 198,
    The_Empress = 199,
    The_Emperor = 200,
    The_Hierophant = 201,
    The_Lovers = 202,
    The_Chariot = 203,
    Justice = 204,
    The_Hermit = 205,
    The_Wheel_of_Fortune = 206,
    Strength = 207,
    The_Hanged_Man = 208,
    Death = 209,
    Temperance = 210,
    The_Devil = 211,
    The_Tower = 212,
    The_Star = 213,
    The_Moon = 214,
    The_Sun = 215,
    Judgement = 216,
    The_World = 217,
    T_END = 218,
    P_BEGIN = 219,
    Mercury = 220,
    Venus = 221,
    Earth = 222,
    Mars = 223,
    Jupiter = 224,
    Saturn = 225,
    Uranus = 226,
    Neptune = 227,
    Pluto = 228,
    Planet_X = 229,
    Ceres = 230,
    Eris = 231,
    P_END = 232,
    H_BEGIN = 233,
    Pair = 234,
    Three_of_a_Kind = 235,
    Full_House = 236,
    Four_of_a_Kind = 237,
    Flush = 238,
    Straight = 239,
    Two_Pair = 240,
    Straight_Flush = 241,
    High_Card = 242,
    Five_of_a_Kind = 243,
    Flush_House = 244,
    Flush_Five = 245,
    H_END = 246,
    S_BEGIN = 247,
    Familiar = 248,
    Grim = 249,
    Incantation = 250,
    Talisman = 251,
    Aura = 252,
    Wraith = 253,
    Sigil = 254,
    Ouija = 255,
    Ectoplasm = 256,
    Immolate = 257,
    Ankh = 258,
    Deja_Vu = 259,
    Hex = 260,
    Trance = 261,
    Medium = 262,
    Cryptid = 263,
    The_Soul = 264,
    Black_Hole = 265,
    S_END = 266,
    ENHANCEMENT_BEGIN = 267,
    No_Enhancement = 268,
    Bonus_Card = 269,
    Mult_Card = 270,
    Wild_Card = 271,
    Glass_Card = 272,
    Steel_Card = 273,
    Stone_Card = 274,
    Gold_Card = 275,
    Lucky_Card = 276,
    ENHANCEMENT_END = 277,
    SEAL_BEGIN = 278,
    No_Seal = 279,
    Gold_Seal = 280,
    Red_Seal = 281,
    Blue_Seal = 282,
    Purple_Seal = 283,
    SEAL_END = 284,
    E_BEGIN = 285,
    No_Edition = 286,
    Foil = 287,
    Holographic = 288,
    Polychrome = 289,
    Negative = 290,
    E_END = 291,
    PACK_BEGIN = 292,
    Arcana_Pack = 293,
    Jumbo_Arcana_Pack = 294,
    Mega_Arcana_Pack = 295,
    Celestial_Pack = 296,
    Jumbo_Celestial_Pack = 297,
    Mega_Celestial_Pack = 298,
    Standard_Pack = 299,
    Jumbo_Standard_Pack = 300,
    Mega_Standard_Pack = 301,
    Buffoon_Pack = 302,
    Jumbo_Buffoon_Pack = 303,
    Mega_Buffoon_Pack = 304,
    Spectral_Pack = 305,
    Jumbo_Spectral_Pack = 306,
    Mega_Spectral_Pack = 307,
    PACK_END = 308,
    TAG_BEGIN = 309,
    Uncommon_Tag = 310,
    Rare_Tag = 311,
    Negative_Tag = 312,
    Foil_Tag = 313,
    Holographic_Tag = 314,
    Polychrome_Tag = 315,
    Investment_Tag = 316,
    Voucher_Tag = 317,
    Boss_Tag = 318,
    Standard_Tag = 319,
    Charm_Tag = 320,
    Meteor_Tag = 321,
    Buffoon_Tag = 322,
    Handy_Tag = 323,
    Garbage_Tag = 324,
    Ethereal_Tag = 325,
    Coupon_Tag = 326,
    Double_Tag = 327,
    Juggle_Tag = 328,
    D6_Tag = 329,
    Top_up_Tag = 330,
    Speed_Tag = 331,
    Orbital_Tag = 332,
    Economy_Tag = 333,
    TAG_END = 334,
    B_BEGIN = 335,
    Small_Blind = 336,
    Big_Blind = 337,
    The_Hook = 338,
    The_Ox = 339,
    The_House = 340,
    The_Wall = 341,
    The_Wheel = 342,
    The_Arm = 343,
    The_Club = 344,
    The_Fish = 345,
    The_Psychic = 346,
    The_Goad = 347,
    The_Water = 348,
    The_Window = 349,
    The_Manacle = 350,
    The_Eye = 351,
    The_Mouth = 352,
    The_Plant = 353,
    The_Serpent = 354,
    The_Pillar = 355,
    The_Needle = 356,
    The_Head = 357,
    The_Tooth = 358,
    The_Flint = 359,
    The_Mark = 360,
    B_F_BEGIN = 361,
    Amber_Acorn = 362,
    Verdant_Leaf = 363,
    Violet_Vessel = 364,
    Crimson_Heart = 365,
    Cerulean_Bell = 366,
    B_F_END = 367,
    B_END = 368,
    SUIT_BEGIN = 369,
    Hearts = 370,
    Clubs = 371,
    Diamonds = 372,
    Spades = 373,
    SUIT_END = 374,
    RANK_BEGIN = 375,
    _2 = 376,
    _3 = 377,
    _4 = 378,
    _5 = 379,
    _6 = 380,
    _7 = 381,
    _8 = 382,
    _9 = 383,
    _10 = 384,
    Jack = 385,
    Queen = 386,
    King = 387,
    Ace = 388,
    RANK_END = 389,
    C_BEGIN = 390,
    C_2 = 391,
    C_3 = 392,
    C_4 = 393,
    C_5 = 394,
    C_6 = 395,
    C_7 = 396,
    C_8 = 397,
    C_9 = 398,
    C_A = 399,
    C_J = 400,
    C_K = 401,
    C_Q = 402,
    C_T = 403,
    D_2 = 404,
    D_3 = 405,
    D_4 = 406,
    D_5 = 407,
    D_6 = 408,
    D_7 = 409,
    D_8 = 410,
    D_9 = 411,
    D_A = 412,
    D_J = 413,
    D_K = 414,
    D_Q = 415,
    D_T = 416,
    H_2 = 417,
    H_3 = 418,
    H_4 = 419,
    H_5 = 420,
    H_6 = 421,
    H_7 = 422,
    H_8 = 423,
    H_9 = 424,
    H_A = 425,
    H_J = 426,
    H_K = 427,
    H_Q = 428,
    H_T = 429,
    S_2 = 430,
    S_3 = 431,
    S_4 = 432,
    S_5 = 433,
    S_6 = 434,
    S_7 = 435,
    S_8 = 436,
    S_9 = 437,
    S_A = 438,
    S_J = 439,
    S_K = 440,
    S_Q = 441,
    S_T = 442,
    C_END = 443,
    D_BEGIN = 444,
    Red_Deck = 445,
    Blue_Deck = 446,
    Yellow_Deck = 447,
    Green_Deck = 448,
    Black_Deck = 449,
    Magic_Deck = 450,
    Nebula_Deck = 451,
    Ghost_Deck = 452,
    Abandoned_Deck = 453,
    Checkered_Deck = 454,
    Zodiac_Deck = 455,
    Painted_Deck = 456,
    Anaglyph_Deck = 457,
    Plasma_Deck = 458,
    Erratic_Deck = 459,
    Challenge_Deck = 460,
    D_END = 461,
    CHAL_BEGIN = 462,
    The_Omelette = 463,
    _15_Minute_City = 464,
    Rich_get_Richer = 465,
    On_a_Knifes_Edge = 466,
    X_ray_Vision = 467,
    Mad_World = 468,
    Luxury_Tax = 469,
    Non_Perishable = 470,
    Medusa = 471,
    Double_or_Nothing = 472,
    Typecast = 473,
    Inflation = 474,
    Bram_Poker = 475,
    Fragile = 476,
    Monolith = 477,
    Blast_Off = 478,
    Five_Card_Draw = 479,
    Golden_Needle = 480,
    Cruelty = 481,
    Jokerless = 482,
    CHAL_END = 483,
    STAKE_BEGIN = 484,
    White_Stake = 485,
    Red_Stake = 486,
    Green_Stake = 487,
    Black_Stake = 488,
    Blue_Stake = 489,
    Purple_Stake = 490,
    Orange_Stake = 491,
    Gold_Stake = 492,
    STAKE_END = 493,
    RARITY_BEGIN = 494,
    Common = 495,
    Uncommon = 496,
    Rare = 497,
    Legendary = 498,
    RARITY_END = 499,
    TYPE_BEGIN = 500,
    T_Joker = 501,
    T_Tarot = 502,
    T_Planet = 503,
    T_Spectral = 504,
    T_Playing_Card = 505,
    TYPE_END = 506,
    ITEMS_END = 507,
}

pub const ITEM_COUNT: usize = Item::ITEMS_END as usize;

impl Item {
    #[inline]
    pub const fn idx(self) -> usize {
        self as usize
    }
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct JokerStickers {
    pub eternal: bool,
    pub perishable: bool,
    pub rental: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct JokerData {
    pub joker: Item,
    pub rarity: Item,
    pub edition: Item,
    pub stickers: JokerStickers,
}

impl Default for JokerData {
    fn default() -> Self {
        Self {
            joker: Item::Joker,
            rarity: Item::Common,
            edition: Item::No_Edition,
            stickers: JokerStickers::default(),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ShopItem {
    pub item_type: Item,
    pub item: Item,
    pub joker_data: JokerData,
}

impl Default for ShopItem {
    fn default() -> Self {
        Self {
            item_type: Item::T_Tarot,
            item: Item::The_Fool,
            joker_data: JokerData::default(),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct WeightedItem {
    pub item: Item,
    pub weight: f64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Pack {
    pub pack_type: Item,
    pub size: usize,
    pub choices: usize,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Card {
    pub base: Item,
    pub enhancement: Item,
    pub edition: Item,
    pub seal: Item,
}

pub const ENHANCEMENTS: [Item; 8] = [
    Item::Bonus_Card,
    Item::Mult_Card,
    Item::Wild_Card,
    Item::Glass_Card,
    Item::Steel_Card,
    Item::Stone_Card,
    Item::Gold_Card,
    Item::Lucky_Card,
];

pub const CARDS: [Item; 52] = [
    Item::C_2,
    Item::C_3,
    Item::C_4,
    Item::C_5,
    Item::C_6,
    Item::C_7,
    Item::C_8,
    Item::C_9,
    Item::C_A,
    Item::C_J,
    Item::C_K,
    Item::C_Q,
    Item::C_T,
    Item::D_2,
    Item::D_3,
    Item::D_4,
    Item::D_5,
    Item::D_6,
    Item::D_7,
    Item::D_8,
    Item::D_9,
    Item::D_A,
    Item::D_J,
    Item::D_K,
    Item::D_Q,
    Item::D_T,
    Item::H_2,
    Item::H_3,
    Item::H_4,
    Item::H_5,
    Item::H_6,
    Item::H_7,
    Item::H_8,
    Item::H_9,
    Item::H_A,
    Item::H_J,
    Item::H_K,
    Item::H_Q,
    Item::H_T,
    Item::S_2,
    Item::S_3,
    Item::S_4,
    Item::S_5,
    Item::S_6,
    Item::S_7,
    Item::S_8,
    Item::S_9,
    Item::S_A,
    Item::S_J,
    Item::S_K,
    Item::S_Q,
    Item::S_T,
];

pub const SUITS: [Item; 4] = [Item::Spades, Item::Hearts, Item::Clubs, Item::Diamonds];

pub const RANKS: [Item; 13] = [
    Item::_2,
    Item::_3,
    Item::_4,
    Item::_5,
    Item::_6,
    Item::_7,
    Item::_8,
    Item::_9,
    Item::_10,
    Item::Jack,
    Item::Queen,
    Item::King,
    Item::Ace,
];

pub const PACKS: [WeightedItem; 16] = [
    WeightedItem {
        item: Item::RETRY,
        weight: 22.42,
    },
    WeightedItem {
        item: Item::Arcana_Pack,
        weight: 4.0,
    },
    WeightedItem {
        item: Item::Jumbo_Arcana_Pack,
        weight: 2.0,
    },
    WeightedItem {
        item: Item::Mega_Arcana_Pack,
        weight: 0.5,
    },
    WeightedItem {
        item: Item::Celestial_Pack,
        weight: 4.0,
    },
    WeightedItem {
        item: Item::Jumbo_Celestial_Pack,
        weight: 2.0,
    },
    WeightedItem {
        item: Item::Mega_Celestial_Pack,
        weight: 0.5,
    },
    WeightedItem {
        item: Item::Standard_Pack,
        weight: 4.0,
    },
    WeightedItem {
        item: Item::Jumbo_Standard_Pack,
        weight: 2.0,
    },
    WeightedItem {
        item: Item::Mega_Standard_Pack,
        weight: 0.5,
    },
    WeightedItem {
        item: Item::Buffoon_Pack,
        weight: 1.2,
    },
    WeightedItem {
        item: Item::Jumbo_Buffoon_Pack,
        weight: 0.6,
    },
    WeightedItem {
        item: Item::Mega_Buffoon_Pack,
        weight: 0.15,
    },
    WeightedItem {
        item: Item::Spectral_Pack,
        weight: 0.6,
    },
    WeightedItem {
        item: Item::Jumbo_Spectral_Pack,
        weight: 0.3,
    },
    WeightedItem {
        item: Item::Mega_Spectral_Pack,
        weight: 0.07,
    },
];

pub const TAROTS: [Item; 22] = [
    Item::The_Fool,
    Item::The_Magician,
    Item::The_High_Priestess,
    Item::The_Empress,
    Item::The_Emperor,
    Item::The_Hierophant,
    Item::The_Lovers,
    Item::The_Chariot,
    Item::Justice,
    Item::The_Hermit,
    Item::The_Wheel_of_Fortune,
    Item::Strength,
    Item::The_Hanged_Man,
    Item::Death,
    Item::Temperance,
    Item::The_Devil,
    Item::The_Tower,
    Item::The_Star,
    Item::The_Moon,
    Item::The_Sun,
    Item::Judgement,
    Item::The_World,
];

pub const PLANETS: [Item; 12] = [
    Item::Mercury,
    Item::Venus,
    Item::Earth,
    Item::Mars,
    Item::Jupiter,
    Item::Saturn,
    Item::Uranus,
    Item::Neptune,
    Item::Pluto,
    Item::Planet_X,
    Item::Ceres,
    Item::Eris,
];

pub const COMMON_JOKERS_100: [Item; 60] = [
    Item::Joker,
    Item::Greedy_Joker,
    Item::Lusty_Joker,
    Item::Wrathful_Joker,
    Item::Gluttonous_Joker,
    Item::Jolly_Joker,
    Item::Zany_Joker,
    Item::Mad_Joker,
    Item::Crazy_Joker,
    Item::Droll_Joker,
    Item::Sly_Joker,
    Item::Wily_Joker,
    Item::Clever_Joker,
    Item::Devious_Joker,
    Item::Crafty_Joker,
    Item::Half_Joker,
    Item::Credit_Card,
    Item::Banner,
    Item::Mystic_Summit,
    Item::_8_Ball,
    Item::Misprint,
    Item::Raised_Fist,
    Item::Chaos_the_Clown,
    Item::Scary_Face,
    Item::Abstract_Joker,
    Item::Delayed_Gratification,
    Item::Gros_Michel,
    Item::Even_Steven,
    Item::Odd_Todd,
    Item::Scholar,
    Item::Business_Card,
    Item::Supernova,
    Item::Ride_the_Bus,
    Item::Egg,
    Item::Runner,
    Item::Ice_Cream,
    Item::Splash,
    Item::Blue_Joker,
    Item::Faceless_Joker,
    Item::Green_Joker,
    Item::Superposition,
    Item::To_Do_List,
    Item::Cavendish,
    Item::Red_Card,
    Item::Square_Joker,
    Item::Riff_raff,
    Item::Photograph,
    Item::Mail_In_Rebate,
    Item::Hallucination,
    Item::Fortune_Teller,
    Item::Juggler,
    Item::Drunkard,
    Item::Golden_Joker,
    Item::Popcorn,
    Item::Walkie_Talkie,
    Item::Smiley_Face,
    Item::Golden_Ticket,
    Item::Swashbuckler,
    Item::Hanging_Chad,
    Item::Shoot_the_Moon,
];

pub const COMMON_JOKERS: [Item; 61] = [
    Item::Joker,
    Item::Greedy_Joker,
    Item::Lusty_Joker,
    Item::Wrathful_Joker,
    Item::Gluttonous_Joker,
    Item::Jolly_Joker,
    Item::Zany_Joker,
    Item::Mad_Joker,
    Item::Crazy_Joker,
    Item::Droll_Joker,
    Item::Sly_Joker,
    Item::Wily_Joker,
    Item::Clever_Joker,
    Item::Devious_Joker,
    Item::Crafty_Joker,
    Item::Half_Joker,
    Item::Credit_Card,
    Item::Banner,
    Item::Mystic_Summit,
    Item::_8_Ball,
    Item::Misprint,
    Item::Raised_Fist,
    Item::Chaos_the_Clown,
    Item::Scary_Face,
    Item::Abstract_Joker,
    Item::Delayed_Gratification,
    Item::Gros_Michel,
    Item::Even_Steven,
    Item::Odd_Todd,
    Item::Scholar,
    Item::Business_Card,
    Item::Supernova,
    Item::Ride_the_Bus,
    Item::Egg,
    Item::Runner,
    Item::Ice_Cream,
    Item::Splash,
    Item::Blue_Joker,
    Item::Faceless_Joker,
    Item::Green_Joker,
    Item::Superposition,
    Item::To_Do_List,
    Item::Cavendish,
    Item::Red_Card,
    Item::Square_Joker,
    Item::Riff_raff,
    Item::Photograph,
    Item::Reserved_Parking,
    Item::Mail_In_Rebate,
    Item::Hallucination,
    Item::Fortune_Teller,
    Item::Juggler,
    Item::Drunkard,
    Item::Golden_Joker,
    Item::Popcorn,
    Item::Walkie_Talkie,
    Item::Smiley_Face,
    Item::Golden_Ticket,
    Item::Swashbuckler,
    Item::Hanging_Chad,
    Item::Shoot_the_Moon,
];

pub const UNCOMMON_JOKERS_100: [Item; 66] = [
    Item::Joker_Stencil,
    Item::Four_Fingers,
    Item::Mime,
    Item::Ceremonial_Dagger,
    Item::Marble_Joker,
    Item::Loyalty_Card,
    Item::Dusk,
    Item::Fibonacci,
    Item::Steel_Joker,
    Item::Hack,
    Item::Pareidolia,
    Item::Space_Joker,
    Item::Burglar,
    Item::Blackboard,
    Item::Constellation,
    Item::Hiker,
    Item::Card_Sharp,
    Item::Madness,
    Item::Vampire,
    Item::Shortcut,
    Item::Hologram,
    Item::Vagabond,
    Item::Cloud_9,
    Item::Rocket,
    Item::Midas_Mask,
    Item::Luchador,
    Item::Gift_Card,
    Item::Turtle_Bean,
    Item::Erosion,
    Item::Reserved_Parking,
    Item::To_the_Moon,
    Item::Stone_Joker,
    Item::Lucky_Cat,
    Item::Bull,
    Item::Diet_Cola,
    Item::Trading_Card,
    Item::Flash_Card,
    Item::Spare_Trousers,
    Item::Ramen,
    Item::Seltzer,
    Item::Castle,
    Item::Mr_Bones,
    Item::Acrobat,
    Item::Sock_and_Buskin,
    Item::Troubadour,
    Item::Certificate,
    Item::Smeared_Joker,
    Item::Throwback,
    Item::Rough_Gem,
    Item::Bloodstone,
    Item::Arrowhead,
    Item::Onyx_Agate,
    Item::Glass_Joker,
    Item::Showman,
    Item::Flower_Pot,
    Item::Merry_Andy,
    Item::Oops_All_6s,
    Item::The_Idol,
    Item::Seeing_Double,
    Item::Matador,
    Item::Stuntman,
    Item::Satellite,
    Item::Cartomancer,
    Item::Astronomer,
    Item::Burnt_Joker,
    Item::Bootstraps,
];

pub const UNCOMMON_JOKERS: [Item; 64] = [
    Item::Joker_Stencil,
    Item::Four_Fingers,
    Item::Mime,
    Item::Ceremonial_Dagger,
    Item::Marble_Joker,
    Item::Loyalty_Card,
    Item::Dusk,
    Item::Fibonacci,
    Item::Steel_Joker,
    Item::Hack,
    Item::Pareidolia,
    Item::Space_Joker,
    Item::Burglar,
    Item::Blackboard,
    Item::Sixth_Sense,
    Item::Constellation,
    Item::Hiker,
    Item::Card_Sharp,
    Item::Madness,
    Item::Seance,
    Item::Vampire,
    Item::Shortcut,
    Item::Hologram,
    Item::Cloud_9,
    Item::Rocket,
    Item::Midas_Mask,
    Item::Luchador,
    Item::Gift_Card,
    Item::Turtle_Bean,
    Item::Erosion,
    Item::To_the_Moon,
    Item::Stone_Joker,
    Item::Lucky_Cat,
    Item::Bull,
    Item::Diet_Cola,
    Item::Trading_Card,
    Item::Flash_Card,
    Item::Spare_Trousers,
    Item::Ramen,
    Item::Seltzer,
    Item::Castle,
    Item::Mr_Bones,
    Item::Acrobat,
    Item::Sock_and_Buskin,
    Item::Troubadour,
    Item::Certificate,
    Item::Smeared_Joker,
    Item::Throwback,
    Item::Rough_Gem,
    Item::Bloodstone,
    Item::Arrowhead,
    Item::Onyx_Agate,
    Item::Glass_Joker,
    Item::Showman,
    Item::Flower_Pot,
    Item::Merry_Andy,
    Item::Oops_All_6s,
    Item::The_Idol,
    Item::Seeing_Double,
    Item::Matador,
    Item::Satellite,
    Item::Cartomancer,
    Item::Astronomer,
    Item::Bootstraps,
];

pub const RARE_JOKERS_100: [Item; 19] = [
    Item::DNA,
    Item::Sixth_Sense,
    Item::Seance,
    Item::Baron,
    Item::Obelisk,
    Item::Baseball_Card,
    Item::Ancient_Joker,
    Item::Campfire,
    Item::Blueprint,
    Item::Wee_Joker,
    Item::Hit_the_Road,
    Item::The_Duo,
    Item::The_Trio,
    Item::The_Family,
    Item::The_Order,
    Item::The_Tribe,
    Item::Invisible_Joker,
    Item::Brainstorm,
    Item::Drivers_License,
];

pub const RARE_JOKERS: [Item; 20] = [
    Item::DNA,
    Item::Vagabond,
    Item::Baron,
    Item::Obelisk,
    Item::Baseball_Card,
    Item::Ancient_Joker,
    Item::Campfire,
    Item::Blueprint,
    Item::Wee_Joker,
    Item::Hit_the_Road,
    Item::The_Duo,
    Item::The_Trio,
    Item::The_Family,
    Item::The_Order,
    Item::The_Tribe,
    Item::Stuntman,
    Item::Invisible_Joker,
    Item::Brainstorm,
    Item::Drivers_License,
    Item::Burnt_Joker,
];

pub const LEGENDARY_JOKERS: [Item; 5] = [
    Item::Canio,
    Item::Triboulet,
    Item::Yorick,
    Item::Chicot,
    Item::Perkeo,
];

pub const VOUCHERS: [Item; 32] = [
    Item::Overstock,
    Item::Overstock_Plus,
    Item::Clearance_Sale,
    Item::Liquidation,
    Item::Hone,
    Item::Glow_Up,
    Item::Reroll_Surplus,
    Item::Reroll_Glut,
    Item::Crystal_Ball,
    Item::Omen_Globe,
    Item::Telescope,
    Item::Observatory,
    Item::Grabber,
    Item::Nacho_Tong,
    Item::Wasteful,
    Item::Recyclomancy,
    Item::Tarot_Merchant,
    Item::Tarot_Tycoon,
    Item::Planet_Merchant,
    Item::Planet_Tycoon,
    Item::Seed_Money,
    Item::Money_Tree,
    Item::Blank,
    Item::Antimatter,
    Item::Magic_Trick,
    Item::Illusion,
    Item::Hieroglyph,
    Item::Petroglyph,
    Item::Directors_Cut,
    Item::Retcon,
    Item::Paint_Brush,
    Item::Palette,
];

pub const SPECTRALS: [Item; 18] = [
    Item::Familiar,
    Item::Grim,
    Item::Incantation,
    Item::Talisman,
    Item::Aura,
    Item::Wraith,
    Item::Sigil,
    Item::Ouija,
    Item::Ectoplasm,
    Item::Immolate,
    Item::Ankh,
    Item::Deja_Vu,
    Item::Hex,
    Item::Trance,
    Item::Medium,
    Item::Cryptid,
    Item::RETRY,
    Item::RETRY,
];

pub const TAGS: [Item; 24] = [
    Item::Uncommon_Tag,
    Item::Rare_Tag,
    Item::Negative_Tag,
    Item::Foil_Tag,
    Item::Holographic_Tag,
    Item::Polychrome_Tag,
    Item::Investment_Tag,
    Item::Voucher_Tag,
    Item::Boss_Tag,
    Item::Standard_Tag,
    Item::Charm_Tag,
    Item::Meteor_Tag,
    Item::Buffoon_Tag,
    Item::Handy_Tag,
    Item::Garbage_Tag,
    Item::Ethereal_Tag,
    Item::Coupon_Tag,
    Item::Double_Tag,
    Item::Juggle_Tag,
    Item::D6_Tag,
    Item::Top_up_Tag,
    Item::Speed_Tag,
    Item::Orbital_Tag,
    Item::Economy_Tag,
];

pub const BOSSES: [Item; 28] = [
    Item::The_Arm,
    Item::The_Club,
    Item::The_Eye,
    Item::Amber_Acorn,
    Item::Cerulean_Bell,
    Item::Crimson_Heart,
    Item::Verdant_Leaf,
    Item::Violet_Vessel,
    Item::The_Fish,
    Item::The_Flint,
    Item::The_Goad,
    Item::The_Head,
    Item::The_Hook,
    Item::The_House,
    Item::The_Manacle,
    Item::The_Mark,
    Item::The_Mouth,
    Item::The_Needle,
    Item::The_Ox,
    Item::The_Pillar,
    Item::The_Plant,
    Item::The_Psychic,
    Item::The_Serpent,
    Item::The_Tooth,
    Item::The_Wall,
    Item::The_Water,
    Item::The_Wheel,
    Item::The_Window,
];

pub fn item_to_string(item: Item) -> &'static str {
    match item {
        Item::RETRY => "RETRY",
        Item::J_BEGIN => "J BEGIN",
        Item::J_C_BEGIN => "J C BEGIN",
        Item::Joker => "Joker",
        Item::Greedy_Joker => "Greedy Joker",
        Item::Lusty_Joker => "Lusty Joker",
        Item::Wrathful_Joker => "Wrathful Joker",
        Item::Gluttonous_Joker => "Gluttonous Joker",
        Item::Jolly_Joker => "Jolly Joker",
        Item::Zany_Joker => "Zany Joker",
        Item::Mad_Joker => "Mad Joker",
        Item::Crazy_Joker => "Crazy Joker",
        Item::Droll_Joker => "Droll Joker",
        Item::Sly_Joker => "Sly Joker",
        Item::Wily_Joker => "Wily Joker",
        Item::Clever_Joker => "Clever Joker",
        Item::Devious_Joker => "Devious Joker",
        Item::Crafty_Joker => "Crafty Joker",
        Item::Half_Joker => "Half Joker",
        Item::Credit_Card => "Credit Card",
        Item::Banner => "Banner",
        Item::Mystic_Summit => "Mystic Summit",
        Item::_8_Ball => "8 Ball",
        Item::Misprint => "Misprint",
        Item::Raised_Fist => "Raised Fist",
        Item::Chaos_the_Clown => "Chaos the Clown",
        Item::Scary_Face => "Scary Face",
        Item::Abstract_Joker => "Abstract Joker",
        Item::Delayed_Gratification => "Delayed Gratification",
        Item::Gros_Michel => "Gros Michel",
        Item::Even_Steven => "Even Steven",
        Item::Odd_Todd => "Odd Todd",
        Item::Scholar => "Scholar",
        Item::Business_Card => "Business Card",
        Item::Supernova => "Supernova",
        Item::Ride_the_Bus => "Ride the Bus",
        Item::Egg => "Egg",
        Item::Runner => "Runner",
        Item::Ice_Cream => "Ice Cream",
        Item::Splash => "Splash",
        Item::Blue_Joker => "Blue Joker",
        Item::Faceless_Joker => "Faceless Joker",
        Item::Green_Joker => "Green Joker",
        Item::Superposition => "Superposition",
        Item::To_Do_List => "To Do List",
        Item::Cavendish => "Cavendish",
        Item::Red_Card => "Red Card",
        Item::Square_Joker => "Square Joker",
        Item::Riff_raff => "Riff-raff",
        Item::Photograph => "Photograph",
        Item::Reserved_Parking => "Reserved Parking",
        Item::Mail_In_Rebate => "Mail-In Rebate",
        Item::Hallucination => "Hallucination",
        Item::Fortune_Teller => "Fortune Teller",
        Item::Juggler => "Juggler",
        Item::Drunkard => "Drunkard",
        Item::Golden_Joker => "Golden Joker",
        Item::Popcorn => "Popcorn",
        Item::Walkie_Talkie => "Walkie Talkie",
        Item::Smiley_Face => "Smiley Face",
        Item::Golden_Ticket => "Golden Ticket",
        Item::Swashbuckler => "Swashbuckler",
        Item::Hanging_Chad => "Hanging Chad",
        Item::Shoot_the_Moon => "Shoot the Moon",
        Item::J_C_END => "J C END",
        Item::J_U_BEGIN => "J U BEGIN",
        Item::Joker_Stencil => "Joker Stencil",
        Item::Four_Fingers => "Four Fingers",
        Item::Mime => "Mime",
        Item::Ceremonial_Dagger => "Ceremonial Dagger",
        Item::Marble_Joker => "Marble Joker",
        Item::Loyalty_Card => "Loyalty Card",
        Item::Dusk => "Dusk",
        Item::Fibonacci => "Fibonacci",
        Item::Steel_Joker => "Steel Joker",
        Item::Hack => "Hack",
        Item::Pareidolia => "Pareidolia",
        Item::Space_Joker => "Space Joker",
        Item::Burglar => "Burglar",
        Item::Blackboard => "Blackboard",
        Item::Sixth_Sense => "Sixth Sense",
        Item::Constellation => "Constellation",
        Item::Hiker => "Hiker",
        Item::Card_Sharp => "Card Sharp",
        Item::Madness => "Madness",
        Item::Seance => "S\u{398}ance",
        Item::Shortcut => "Shortcut",
        Item::Hologram => "Hologram",
        Item::Cloud_9 => "Cloud 9",
        Item::Rocket => "Rocket",
        Item::Midas_Mask => "Midas Mask",
        Item::Luchador => "Luchador",
        Item::Gift_Card => "Gift Card",
        Item::Turtle_Bean => "Turtle Bean",
        Item::Erosion => "Erosion",
        Item::To_the_Moon => "To the Moon",
        Item::Stone_Joker => "Stone Joker",
        Item::Lucky_Cat => "Lucky Cat",
        Item::Bull => "Bull",
        Item::Diet_Cola => "Diet Cola",
        Item::Trading_Card => "Trading Card",
        Item::Flash_Card => "Flash Card",
        Item::Spare_Trousers => "Spare Trousers",
        Item::Ramen => "Ramen",
        Item::Seltzer => "Seltzer",
        Item::Castle => "Castle",
        Item::Mr_Bones => "Mr. Bones",
        Item::Acrobat => "Acrobat",
        Item::Sock_and_Buskin => "Sock and Buskin",
        Item::Troubadour => "Troubadour",
        Item::Certificate => "Certificate",
        Item::Smeared_Joker => "Smeared Joker",
        Item::Throwback => "Throwback",
        Item::Rough_Gem => "Rough Gem",
        Item::Bloodstone => "Bloodstone",
        Item::Arrowhead => "Arrowhead",
        Item::Onyx_Agate => "Onyx Agate",
        Item::Glass_Joker => "Glass Joker",
        Item::Showman => "Showman",
        Item::Flower_Pot => "Flower Pot",
        Item::Merry_Andy => "Merry Andy",
        Item::Oops_All_6s => "Oops! All 6s",
        Item::The_Idol => "The Idol",
        Item::Seeing_Double => "Seeing Double",
        Item::Matador => "Matador",
        Item::Stuntman => "Stuntman",
        Item::Satellite => "Satellite",
        Item::Cartomancer => "Cartomancer",
        Item::Astronomer => "Astronomer",
        Item::Bootstraps => "Bootstraps",
        Item::J_U_END => "J U END",
        Item::J_R_BEGIN => "J R BEGIN",
        Item::DNA => "DNA",
        Item::Vampire => "Vampire",
        Item::Vagabond => "Vagabond",
        Item::Baron => "Baron",
        Item::Obelisk => "Obelisk",
        Item::Baseball_Card => "Baseball Card",
        Item::Ancient_Joker => "Ancient Joker",
        Item::Campfire => "Campfire",
        Item::Blueprint => "Blueprint",
        Item::Wee_Joker => "Wee Joker",
        Item::Hit_the_Road => "Hit the Road",
        Item::The_Duo => "The Duo",
        Item::The_Trio => "The Trio",
        Item::The_Family => "The Family",
        Item::The_Order => "The Order",
        Item::The_Tribe => "The Tribe",
        Item::Invisible_Joker => "Invisible Joker",
        Item::Brainstorm => "Brainstorm",
        Item::Drivers_License => "Driver's License",
        Item::Burnt_Joker => "Burnt Joker",
        Item::J_R_END => "J R END",
        Item::J_L_BEGIN => "J L BEGIN",
        Item::Canio => "Canio",
        Item::Triboulet => "Triboulet",
        Item::Yorick => "Yorick",
        Item::Chicot => "Chicot",
        Item::Perkeo => "Perkeo",
        Item::J_L_END => "J L END",
        Item::J_END => "J END",
        Item::V_BEGIN => "V BEGIN",
        Item::Overstock => "Overstock",
        Item::Overstock_Plus => "Overstock Plus",
        Item::Clearance_Sale => "Clearance Sale",
        Item::Liquidation => "Liquidation",
        Item::Hone => "Hone",
        Item::Glow_Up => "Glow Up",
        Item::Reroll_Surplus => "Reroll Surplus",
        Item::Reroll_Glut => "Reroll Glut",
        Item::Crystal_Ball => "Crystal Ball",
        Item::Omen_Globe => "Omen Globe",
        Item::Telescope => "Telescope",
        Item::Observatory => "Observatory",
        Item::Grabber => "Grabber",
        Item::Nacho_Tong => "Nacho Tong",
        Item::Wasteful => "Wasteful",
        Item::Recyclomancy => "Recyclomancy",
        Item::Tarot_Merchant => "Tarot Merchant",
        Item::Tarot_Tycoon => "Tarot Tycoon",
        Item::Planet_Merchant => "Planet Merchant",
        Item::Planet_Tycoon => "Planet Tycoon",
        Item::Seed_Money => "Seed Money",
        Item::Money_Tree => "Money Tree",
        Item::Blank => "Blank",
        Item::Antimatter => "Antimatter",
        Item::Magic_Trick => "Magic Trick",
        Item::Illusion => "Illusion",
        Item::Hieroglyph => "Hieroglyph",
        Item::Petroglyph => "Petroglyph",
        Item::Directors_Cut => "Director's Cut",
        Item::Retcon => "Retcon",
        Item::Paint_Brush => "Paint Brush",
        Item::Palette => "Palette",
        Item::V_END => "V END",
        Item::T_BEGIN => "T BEGIN",
        Item::The_Fool => "The Fool",
        Item::The_Magician => "The Magician",
        Item::The_High_Priestess => "The High Priestess",
        Item::The_Empress => "The Empress",
        Item::The_Emperor => "The Emperor",
        Item::The_Hierophant => "The Hierophant",
        Item::The_Lovers => "The Lovers",
        Item::The_Chariot => "The Chariot",
        Item::Justice => "Justice",
        Item::The_Hermit => "The Hermit",
        Item::The_Wheel_of_Fortune => "The Wheel of Fortune",
        Item::Strength => "Strength",
        Item::The_Hanged_Man => "The Hanged Man",
        Item::Death => "Death",
        Item::Temperance => "Temperance",
        Item::The_Devil => "The Devil",
        Item::The_Tower => "The Tower",
        Item::The_Star => "The Star",
        Item::The_Moon => "The Moon",
        Item::The_Sun => "The Sun",
        Item::Judgement => "Judgement",
        Item::The_World => "The World",
        Item::T_END => "T END",
        Item::P_BEGIN => "P BEGIN",
        Item::Mercury => "Mercury",
        Item::Venus => "Venus",
        Item::Earth => "Earth",
        Item::Mars => "Mars",
        Item::Jupiter => "Jupiter",
        Item::Saturn => "Saturn",
        Item::Uranus => "Uranus",
        Item::Neptune => "Neptune",
        Item::Pluto => "Pluto",
        Item::Planet_X => "Planet X",
        Item::Ceres => "Ceres",
        Item::Eris => "Eris",
        Item::P_END => "P END",
        Item::H_BEGIN => "H BEGIN",
        Item::Pair => "Pair",
        Item::Three_of_a_Kind => "Three of a Kind",
        Item::Full_House => "Full House",
        Item::Four_of_a_Kind => "Four of a Kind",
        Item::Flush => "Flush",
        Item::Straight => "Straight",
        Item::Two_Pair => "Two Pair",
        Item::Straight_Flush => "Straight Flush",
        Item::High_Card => "High Card",
        Item::Five_of_a_Kind => "Five of a Kind",
        Item::Flush_House => "Flush House",
        Item::Flush_Five => "Flush Five",
        Item::H_END => "H END",
        Item::S_BEGIN => "S BEGIN",
        Item::Familiar => "Familiar",
        Item::Grim => "Grim",
        Item::Incantation => "Incantation",
        Item::Talisman => "Talisman",
        Item::Aura => "Aura",
        Item::Wraith => "Wraith",
        Item::Sigil => "Sigil",
        Item::Ouija => "Ouija",
        Item::Ectoplasm => "Ectoplasm",
        Item::Immolate => "Immolate",
        Item::Ankh => "Ankh",
        Item::Deja_Vu => "Deja Vu",
        Item::Hex => "Hex",
        Item::Trance => "Trance",
        Item::Medium => "Medium",
        Item::Cryptid => "Cryptid",
        Item::The_Soul => "The Soul",
        Item::Black_Hole => "Black Hole",
        Item::S_END => "S END",
        Item::ENHANCEMENT_BEGIN => "ENHANCEMENT BEGIN",
        Item::No_Enhancement => "No Enhancement",
        Item::Bonus_Card => "Bonus Card",
        Item::Mult_Card => "Mult Card",
        Item::Wild_Card => "Wild Card",
        Item::Glass_Card => "Glass Card",
        Item::Steel_Card => "Steel Card",
        Item::Stone_Card => "Stone Card",
        Item::Gold_Card => "Gold Card",
        Item::Lucky_Card => "Lucky Card",
        Item::ENHANCEMENT_END => "ENHANCEMENT END",
        Item::SEAL_BEGIN => "SEAL BEGIN",
        Item::No_Seal => "No Seal",
        Item::Gold_Seal => "Gold Seal",
        Item::Red_Seal => "Red Seal",
        Item::Blue_Seal => "Blue Seal",
        Item::Purple_Seal => "Purple Seal",
        Item::SEAL_END => "SEAL END",
        Item::E_BEGIN => "E BEGIN",
        Item::No_Edition => "No Edition",
        Item::Foil => "Foil",
        Item::Holographic => "Holographic",
        Item::Polychrome => "Polychrome",
        Item::Negative => "Negative",
        Item::E_END => "E END",
        Item::PACK_BEGIN => "PACK BEGIN",
        Item::Arcana_Pack => "Arcana Pack",
        Item::Jumbo_Arcana_Pack => "Jumbo Arcana Pack",
        Item::Mega_Arcana_Pack => "Mega Arcana Pack",
        Item::Celestial_Pack => "Celestial Pack",
        Item::Jumbo_Celestial_Pack => "Jumbo Celestial Pack",
        Item::Mega_Celestial_Pack => "Mega Celestial Pack",
        Item::Standard_Pack => "Standard Pack",
        Item::Jumbo_Standard_Pack => "Jumbo Standard Pack",
        Item::Mega_Standard_Pack => "Mega Standard Pack",
        Item::Buffoon_Pack => "Buffoon Pack",
        Item::Jumbo_Buffoon_Pack => "Jumbo Buffoon Pack",
        Item::Mega_Buffoon_Pack => "Mega Buffoon Pack",
        Item::Spectral_Pack => "Spectral Pack",
        Item::Jumbo_Spectral_Pack => "Jumbo Spectral Pack",
        Item::Mega_Spectral_Pack => "Mega Spectral Pack",
        Item::PACK_END => "PACK END",
        Item::TAG_BEGIN => "TAG BEGIN",
        Item::Uncommon_Tag => "Uncommon Tag",
        Item::Rare_Tag => "Rare Tag",
        Item::Negative_Tag => "Negative Tag",
        Item::Foil_Tag => "Foil Tag",
        Item::Holographic_Tag => "Holographic Tag",
        Item::Polychrome_Tag => "Polychrome Tag",
        Item::Investment_Tag => "Investment Tag",
        Item::Voucher_Tag => "Voucher Tag",
        Item::Boss_Tag => "Boss Tag",
        Item::Standard_Tag => "Standard Tag",
        Item::Charm_Tag => "Charm Tag",
        Item::Meteor_Tag => "Meteor Tag",
        Item::Buffoon_Tag => "Buffoon Tag",
        Item::Handy_Tag => "Handy Tag",
        Item::Garbage_Tag => "Garbage Tag",
        Item::Ethereal_Tag => "Ethereal Tag",
        Item::Coupon_Tag => "Coupon Tag",
        Item::Double_Tag => "Double Tag",
        Item::Juggle_Tag => "Juggle Tag",
        Item::D6_Tag => "D6 Tag",
        Item::Top_up_Tag => "Top-up Tag",
        Item::Speed_Tag => "Speed Tag",
        Item::Orbital_Tag => "Orbital Tag",
        Item::Economy_Tag => "Economy Tag",
        Item::TAG_END => "TAG END",
        Item::B_BEGIN => "B BEGIN",
        Item::Small_Blind => "Small Blind",
        Item::Big_Blind => "Big Blind",
        Item::The_Hook => "The Hook",
        Item::The_Ox => "The Ox",
        Item::The_House => "The House",
        Item::The_Wall => "The Wall",
        Item::The_Wheel => "The Wheel",
        Item::The_Arm => "The Arm",
        Item::The_Club => "The Club",
        Item::The_Fish => "The Fish",
        Item::The_Psychic => "The Psychic",
        Item::The_Goad => "The Goad",
        Item::The_Water => "The Water",
        Item::The_Window => "The Window",
        Item::The_Manacle => "The Manacle",
        Item::The_Eye => "The Eye",
        Item::The_Mouth => "The Mouth",
        Item::The_Plant => "The Plant",
        Item::The_Serpent => "The Serpent",
        Item::The_Pillar => "The Pillar",
        Item::The_Needle => "The Needle",
        Item::The_Head => "The Head",
        Item::The_Tooth => "The Tooth",
        Item::The_Flint => "The Flint",
        Item::The_Mark => "The Mark",
        Item::B_F_BEGIN => "B F BEGIN",
        Item::Amber_Acorn => "Amber Acorn",
        Item::Verdant_Leaf => "Verdant Leaf",
        Item::Violet_Vessel => "Violet Vessel",
        Item::Crimson_Heart => "Crimson Heart",
        Item::Cerulean_Bell => "Cerulean Bell",
        Item::B_F_END => "B F END",
        Item::B_END => "B END",
        Item::SUIT_BEGIN => "SUIT BEGIN",
        Item::Hearts => "Hearts",
        Item::Clubs => "Clubs",
        Item::Diamonds => "Diamonds",
        Item::Spades => "Spades",
        Item::SUIT_END => "SUIT END",
        Item::RANK_BEGIN => "RANK BEGIN",
        Item::_2 => "2",
        Item::_3 => "3",
        Item::_4 => "4",
        Item::_5 => "5",
        Item::_6 => "6",
        Item::_7 => "7",
        Item::_8 => "8",
        Item::_9 => "9",
        Item::_10 => "10",
        Item::Jack => "Jack",
        Item::Queen => "Queen",
        Item::King => "King",
        Item::Ace => "Ace",
        Item::RANK_END => "RANK END",
        Item::C_BEGIN => "C BEGIN",
        Item::C_2 => "C 2",
        Item::C_3 => "C 3",
        Item::C_4 => "C 4",
        Item::C_5 => "C 5",
        Item::C_6 => "C 6",
        Item::C_7 => "C 7",
        Item::C_8 => "C 8",
        Item::C_9 => "C 9",
        Item::C_A => "C A",
        Item::C_J => "C J",
        Item::C_K => "C K",
        Item::C_Q => "C Q",
        Item::C_T => "C T",
        Item::D_2 => "D 2",
        Item::D_3 => "D 3",
        Item::D_4 => "D 4",
        Item::D_5 => "D 5",
        Item::D_6 => "D 6",
        Item::D_7 => "D 7",
        Item::D_8 => "D 8",
        Item::D_9 => "D 9",
        Item::D_A => "D A",
        Item::D_J => "D J",
        Item::D_K => "D K",
        Item::D_Q => "D Q",
        Item::D_T => "D T",
        Item::H_2 => "H 2",
        Item::H_3 => "H 3",
        Item::H_4 => "H 4",
        Item::H_5 => "H 5",
        Item::H_6 => "H 6",
        Item::H_7 => "H 7",
        Item::H_8 => "H 8",
        Item::H_9 => "H 9",
        Item::H_A => "H A",
        Item::H_J => "H J",
        Item::H_K => "H K",
        Item::H_Q => "H Q",
        Item::H_T => "H T",
        Item::S_2 => "S 2",
        Item::S_3 => "S 3",
        Item::S_4 => "S 4",
        Item::S_5 => "S 5",
        Item::S_6 => "S 6",
        Item::S_7 => "S 7",
        Item::S_8 => "S 8",
        Item::S_9 => "S 9",
        Item::S_A => "S A",
        Item::S_J => "S J",
        Item::S_K => "S K",
        Item::S_Q => "S Q",
        Item::S_T => "S T",
        Item::C_END => "C END",
        Item::D_BEGIN => "D BEGIN",
        Item::Red_Deck => "Red Deck",
        Item::Blue_Deck => "Blue Deck",
        Item::Yellow_Deck => "Yellow Deck",
        Item::Green_Deck => "Green Deck",
        Item::Black_Deck => "Black Deck",
        Item::Magic_Deck => "Magic Deck",
        Item::Nebula_Deck => "Nebula Deck",
        Item::Ghost_Deck => "Ghost Deck",
        Item::Abandoned_Deck => "Abandoned Deck",
        Item::Checkered_Deck => "Checkered Deck",
        Item::Zodiac_Deck => "Zodiac Deck",
        Item::Painted_Deck => "Painted Deck",
        Item::Anaglyph_Deck => "Anaglyph Deck",
        Item::Plasma_Deck => "Plasma Deck",
        Item::Erratic_Deck => "Erratic Deck",
        Item::Challenge_Deck => "Challenge Deck",
        Item::D_END => "D END",
        Item::CHAL_BEGIN => "CHAL BEGIN",
        Item::The_Omelette => "The Omelette",
        Item::_15_Minute_City => "15 Minute City",
        Item::Rich_get_Richer => "Rich get Richer",
        Item::On_a_Knifes_Edge => "On a Knife's Edge",
        Item::X_ray_Vision => "X-ray Vision",
        Item::Mad_World => "Mad World",
        Item::Luxury_Tax => "Luxury Tax",
        Item::Non_Perishable => "Non-Perishable",
        Item::Medusa => "Medusa",
        Item::Double_or_Nothing => "Double or Nothing",
        Item::Typecast => "Typecast",
        Item::Inflation => "Inflation",
        Item::Bram_Poker => "Bram Poker",
        Item::Fragile => "Fragile",
        Item::Monolith => "Monolith",
        Item::Blast_Off => "Blast Off",
        Item::Five_Card_Draw => "Five-Card Draw",
        Item::Golden_Needle => "Golden Needle",
        Item::Cruelty => "Cruelty",
        Item::Jokerless => "Jokerless",
        Item::CHAL_END => "CHAL END",
        Item::STAKE_BEGIN => "STAKE BEGIN",
        Item::White_Stake => "White Stake",
        Item::Red_Stake => "Red Stake",
        Item::Green_Stake => "Green Stake",
        Item::Black_Stake => "Black Stake",
        Item::Blue_Stake => "Blue Stake",
        Item::Purple_Stake => "Purple Stake",
        Item::Orange_Stake => "Orange Stake",
        Item::Gold_Stake => "Gold Stake",
        Item::STAKE_END => "STAKE END",
        Item::RARITY_BEGIN => "RARITY BEGIN",
        Item::Common => "Common",
        Item::Uncommon => "Uncommon",
        Item::Rare => "Rare",
        Item::Legendary => "Legendary",
        Item::RARITY_END => "RARITY END",
        Item::TYPE_BEGIN => "TYPE BEGIN",
        Item::T_Joker => "T Joker",
        Item::T_Tarot => "T Tarot",
        Item::T_Planet => "T Planet",
        Item::T_Spectral => "T Spectral",
        Item::T_Playing_Card => "T Playing Card",
        Item::TYPE_END => "TYPE END",
        _ => "UNKNOWN ITEM",
    }
}

pub fn string_to_item(name: &str) -> Item {
    match name {
        "RETRY" => Item::RETRY,
        "J BEGIN" => Item::J_BEGIN,
        "J C BEGIN" => Item::J_C_BEGIN,
        "Joker" => Item::Joker,
        "Greedy Joker" => Item::Greedy_Joker,
        "Lusty Joker" => Item::Lusty_Joker,
        "Wrathful Joker" => Item::Wrathful_Joker,
        "Gluttonous Joker" => Item::Gluttonous_Joker,
        "Jolly Joker" => Item::Jolly_Joker,
        "Zany Joker" => Item::Zany_Joker,
        "Mad Joker" => Item::Mad_Joker,
        "Crazy Joker" => Item::Crazy_Joker,
        "Droll Joker" => Item::Droll_Joker,
        "Sly Joker" => Item::Sly_Joker,
        "Wily Joker" => Item::Wily_Joker,
        "Clever Joker" => Item::Clever_Joker,
        "Devious Joker" => Item::Devious_Joker,
        "Crafty Joker" => Item::Crafty_Joker,
        "Half Joker" => Item::Half_Joker,
        "Credit Card" => Item::Credit_Card,
        "Banner" => Item::Banner,
        "Mystic Summit" => Item::Mystic_Summit,
        "8 Ball" => Item::_8_Ball,
        "Misprint" => Item::Misprint,
        "Raised Fist" => Item::Raised_Fist,
        "Chaos the Clown" => Item::Chaos_the_Clown,
        "Scary Face" => Item::Scary_Face,
        "Abstract Joker" => Item::Abstract_Joker,
        "Delayed Gratification" => Item::Delayed_Gratification,
        "Gros Michel" => Item::Gros_Michel,
        "Even Steven" => Item::Even_Steven,
        "Odd Todd" => Item::Odd_Todd,
        "Scholar" => Item::Scholar,
        "Business Card" => Item::Business_Card,
        "Supernova" => Item::Supernova,
        "Ride the Bus" => Item::Ride_the_Bus,
        "Egg" => Item::Egg,
        "Runner" => Item::Runner,
        "Ice Cream" => Item::Ice_Cream,
        "Splash" => Item::Splash,
        "Blue Joker" => Item::Blue_Joker,
        "Faceless Joker" => Item::Faceless_Joker,
        "Green Joker" => Item::Green_Joker,
        "Superposition" => Item::Superposition,
        "To Do List" => Item::To_Do_List,
        "Cavendish" => Item::Cavendish,
        "Red Card" => Item::Red_Card,
        "Square Joker" => Item::Square_Joker,
        "Riff-raff" => Item::Riff_raff,
        "Photograph" => Item::Photograph,
        "Reserved Parking" => Item::Reserved_Parking,
        "Mail-In Rebate" => Item::Mail_In_Rebate,
        "Hallucination" => Item::Hallucination,
        "Fortune Teller" => Item::Fortune_Teller,
        "Juggler" => Item::Juggler,
        "Drunkard" => Item::Drunkard,
        "Golden Joker" => Item::Golden_Joker,
        "Popcorn" => Item::Popcorn,
        "Walkie Talkie" => Item::Walkie_Talkie,
        "Smiley Face" => Item::Smiley_Face,
        "Golden Ticket" => Item::Golden_Ticket,
        "Swashbuckler" => Item::Swashbuckler,
        "Hanging Chad" => Item::Hanging_Chad,
        "Shoot the Moon" => Item::Shoot_the_Moon,
        "J C END" => Item::J_C_END,
        "J U BEGIN" => Item::J_U_BEGIN,
        "Joker Stencil" => Item::Joker_Stencil,
        "Four Fingers" => Item::Four_Fingers,
        "Mime" => Item::Mime,
        "Ceremonial Dagger" => Item::Ceremonial_Dagger,
        "Marble Joker" => Item::Marble_Joker,
        "Loyalty Card" => Item::Loyalty_Card,
        "Dusk" => Item::Dusk,
        "Fibonacci" => Item::Fibonacci,
        "Steel Joker" => Item::Steel_Joker,
        "Hack" => Item::Hack,
        "Pareidolia" => Item::Pareidolia,
        "Space Joker" => Item::Space_Joker,
        "Burglar" => Item::Burglar,
        "Blackboard" => Item::Blackboard,
        "Sixth Sense" => Item::Sixth_Sense,
        "Constellation" => Item::Constellation,
        "Hiker" => Item::Hiker,
        "Card Sharp" => Item::Card_Sharp,
        "Madness" => Item::Madness,
        "S\u{398}ance" => Item::Seance,
        "Shortcut" => Item::Shortcut,
        "Hologram" => Item::Hologram,
        "Cloud 9" => Item::Cloud_9,
        "Rocket" => Item::Rocket,
        "Midas Mask" => Item::Midas_Mask,
        "Luchador" => Item::Luchador,
        "Gift Card" => Item::Gift_Card,
        "Turtle Bean" => Item::Turtle_Bean,
        "Erosion" => Item::Erosion,
        "To the Moon" => Item::To_the_Moon,
        "Stone Joker" => Item::Stone_Joker,
        "Lucky Cat" => Item::Lucky_Cat,
        "Bull" => Item::Bull,
        "Diet Cola" => Item::Diet_Cola,
        "Trading Card" => Item::Trading_Card,
        "Flash Card" => Item::Flash_Card,
        "Spare Trousers" => Item::Spare_Trousers,
        "Ramen" => Item::Ramen,
        "Seltzer" => Item::Seltzer,
        "Castle" => Item::Castle,
        "Mr. Bones" => Item::Mr_Bones,
        "Acrobat" => Item::Acrobat,
        "Sock and Buskin" => Item::Sock_and_Buskin,
        "Troubadour" => Item::Troubadour,
        "Certificate" => Item::Certificate,
        "Smeared Joker" => Item::Smeared_Joker,
        "Throwback" => Item::Throwback,
        "Rough Gem" => Item::Rough_Gem,
        "Bloodstone" => Item::Bloodstone,
        "Arrowhead" => Item::Arrowhead,
        "Onyx Agate" => Item::Onyx_Agate,
        "Glass Joker" => Item::Glass_Joker,
        "Showman" => Item::Showman,
        "Flower Pot" => Item::Flower_Pot,
        "Merry Andy" => Item::Merry_Andy,
        "Oops! All 6s" => Item::Oops_All_6s,
        "The Idol" => Item::The_Idol,
        "Seeing Double" => Item::Seeing_Double,
        "Matador" => Item::Matador,
        "Stuntman" => Item::Stuntman,
        "Satellite" => Item::Satellite,
        "Cartomancer" => Item::Cartomancer,
        "Astronomer" => Item::Astronomer,
        "Bootstraps" => Item::Bootstraps,
        "J U END" => Item::J_U_END,
        "J R BEGIN" => Item::J_R_BEGIN,
        "DNA" => Item::DNA,
        "Vampire" => Item::Vampire,
        "Vagabond" => Item::Vagabond,
        "Baron" => Item::Baron,
        "Obelisk" => Item::Obelisk,
        "Baseball Card" => Item::Baseball_Card,
        "Ancient Joker" => Item::Ancient_Joker,
        "Campfire" => Item::Campfire,
        "Blueprint" => Item::Blueprint,
        "Wee Joker" => Item::Wee_Joker,
        "Hit the Road" => Item::Hit_the_Road,
        "The Duo" => Item::The_Duo,
        "The Trio" => Item::The_Trio,
        "The Family" => Item::The_Family,
        "The Order" => Item::The_Order,
        "The Tribe" => Item::The_Tribe,
        "Invisible Joker" => Item::Invisible_Joker,
        "Brainstorm" => Item::Brainstorm,
        "Driver's License" => Item::Drivers_License,
        "Burnt Joker" => Item::Burnt_Joker,
        "J R END" => Item::J_R_END,
        "J L BEGIN" => Item::J_L_BEGIN,
        "Canio" => Item::Canio,
        "Triboulet" => Item::Triboulet,
        "Yorick" => Item::Yorick,
        "Chicot" => Item::Chicot,
        "Perkeo" => Item::Perkeo,
        "J L END" => Item::J_L_END,
        "J END" => Item::J_END,
        "V BEGIN" => Item::V_BEGIN,
        "Overstock" => Item::Overstock,
        "Overstock Plus" => Item::Overstock_Plus,
        "Clearance Sale" => Item::Clearance_Sale,
        "Liquidation" => Item::Liquidation,
        "Hone" => Item::Hone,
        "Glow Up" => Item::Glow_Up,
        "Reroll Surplus" => Item::Reroll_Surplus,
        "Reroll Glut" => Item::Reroll_Glut,
        "Crystal Ball" => Item::Crystal_Ball,
        "Omen Globe" => Item::Omen_Globe,
        "Telescope" => Item::Telescope,
        "Observatory" => Item::Observatory,
        "Grabber" => Item::Grabber,
        "Nacho Tong" => Item::Nacho_Tong,
        "Wasteful" => Item::Wasteful,
        "Recyclomancy" => Item::Recyclomancy,
        "Tarot Merchant" => Item::Tarot_Merchant,
        "Tarot Tycoon" => Item::Tarot_Tycoon,
        "Planet Merchant" => Item::Planet_Merchant,
        "Planet Tycoon" => Item::Planet_Tycoon,
        "Seed Money" => Item::Seed_Money,
        "Money Tree" => Item::Money_Tree,
        "Blank" => Item::Blank,
        "Antimatter" => Item::Antimatter,
        "Magic Trick" => Item::Magic_Trick,
        "Illusion" => Item::Illusion,
        "Hieroglyph" => Item::Hieroglyph,
        "Petroglyph" => Item::Petroglyph,
        "Director's Cut" => Item::Directors_Cut,
        "Retcon" => Item::Retcon,
        "Paint Brush" => Item::Paint_Brush,
        "Palette" => Item::Palette,
        "V END" => Item::V_END,
        "T BEGIN" => Item::T_BEGIN,
        "The Fool" => Item::The_Fool,
        "The Magician" => Item::The_Magician,
        "The High Priestess" => Item::The_High_Priestess,
        "The Empress" => Item::The_Empress,
        "The Emperor" => Item::The_Emperor,
        "The Hierophant" => Item::The_Hierophant,
        "The Lovers" => Item::The_Lovers,
        "The Chariot" => Item::The_Chariot,
        "Justice" => Item::Justice,
        "The Hermit" => Item::The_Hermit,
        "The Wheel of Fortune" => Item::The_Wheel_of_Fortune,
        "Strength" => Item::Strength,
        "The Hanged Man" => Item::The_Hanged_Man,
        "Death" => Item::Death,
        "Temperance" => Item::Temperance,
        "The Devil" => Item::The_Devil,
        "The Tower" => Item::The_Tower,
        "The Star" => Item::The_Star,
        "The Moon" => Item::The_Moon,
        "The Sun" => Item::The_Sun,
        "Judgement" => Item::Judgement,
        "The World" => Item::The_World,
        "T END" => Item::T_END,
        "P BEGIN" => Item::P_BEGIN,
        "Mercury" => Item::Mercury,
        "Venus" => Item::Venus,
        "Earth" => Item::Earth,
        "Mars" => Item::Mars,
        "Jupiter" => Item::Jupiter,
        "Saturn" => Item::Saturn,
        "Uranus" => Item::Uranus,
        "Neptune" => Item::Neptune,
        "Pluto" => Item::Pluto,
        "Planet X" => Item::Planet_X,
        "Ceres" => Item::Ceres,
        "Eris" => Item::Eris,
        "P END" => Item::P_END,
        "H BEGIN" => Item::H_BEGIN,
        "Pair" => Item::Pair,
        "Three of a Kind" => Item::Three_of_a_Kind,
        "Full House" => Item::Full_House,
        "Four of a Kind" => Item::Four_of_a_Kind,
        "Flush" => Item::Flush,
        "Straight" => Item::Straight,
        "Two Pair" => Item::Two_Pair,
        "Straight Flush" => Item::Straight_Flush,
        "High Card" => Item::High_Card,
        "Five of a Kind" => Item::Five_of_a_Kind,
        "Flush House" => Item::Flush_House,
        "Flush Five" => Item::Flush_Five,
        "H END" => Item::H_END,
        "S BEGIN" => Item::S_BEGIN,
        "Familiar" => Item::Familiar,
        "Grim" => Item::Grim,
        "Incantation" => Item::Incantation,
        "Talisman" => Item::Talisman,
        "Aura" => Item::Aura,
        "Wraith" => Item::Wraith,
        "Sigil" => Item::Sigil,
        "Ouija" => Item::Ouija,
        "Ectoplasm" => Item::Ectoplasm,
        "Immolate" => Item::Immolate,
        "Ankh" => Item::Ankh,
        "Deja Vu" => Item::Deja_Vu,
        "Hex" => Item::Hex,
        "Trance" => Item::Trance,
        "Medium" => Item::Medium,
        "Cryptid" => Item::Cryptid,
        "The Soul" => Item::The_Soul,
        "Black Hole" => Item::Black_Hole,
        "S END" => Item::S_END,
        "ENHANCEMENT BEGIN" => Item::ENHANCEMENT_BEGIN,
        "No Enhancement" => Item::No_Enhancement,
        "Bonus Card" => Item::Bonus_Card,
        "Mult Card" => Item::Mult_Card,
        "Wild Card" => Item::Wild_Card,
        "Glass Card" => Item::Glass_Card,
        "Steel Card" => Item::Steel_Card,
        "Stone Card" => Item::Stone_Card,
        "Gold Card" => Item::Gold_Card,
        "Lucky Card" => Item::Lucky_Card,
        "ENHANCEMENT END" => Item::ENHANCEMENT_END,
        "SEAL BEGIN" => Item::SEAL_BEGIN,
        "No Seal" => Item::No_Seal,
        "Gold Seal" => Item::Gold_Seal,
        "Red Seal" => Item::Red_Seal,
        "Blue Seal" => Item::Blue_Seal,
        "Purple Seal" => Item::Purple_Seal,
        "SEAL END" => Item::SEAL_END,
        "E BEGIN" => Item::E_BEGIN,
        "No Edition" => Item::No_Edition,
        "Foil" => Item::Foil,
        "Holographic" => Item::Holographic,
        "Polychrome" => Item::Polychrome,
        "Negative" => Item::Negative,
        "E END" => Item::E_END,
        "PACK BEGIN" => Item::PACK_BEGIN,
        "Arcana Pack" => Item::Arcana_Pack,
        "Jumbo Arcana Pack" => Item::Jumbo_Arcana_Pack,
        "Mega Arcana Pack" => Item::Mega_Arcana_Pack,
        "Celestial Pack" => Item::Celestial_Pack,
        "Jumbo Celestial Pack" => Item::Jumbo_Celestial_Pack,
        "Mega Celestial Pack" => Item::Mega_Celestial_Pack,
        "Standard Pack" => Item::Standard_Pack,
        "Jumbo Standard Pack" => Item::Jumbo_Standard_Pack,
        "Mega Standard Pack" => Item::Mega_Standard_Pack,
        "Buffoon Pack" => Item::Buffoon_Pack,
        "Jumbo Buffoon Pack" => Item::Jumbo_Buffoon_Pack,
        "Mega Buffoon Pack" => Item::Mega_Buffoon_Pack,
        "Spectral Pack" => Item::Spectral_Pack,
        "Jumbo Spectral Pack" => Item::Jumbo_Spectral_Pack,
        "Mega Spectral Pack" => Item::Mega_Spectral_Pack,
        "PACK END" => Item::PACK_END,
        "TAG BEGIN" => Item::TAG_BEGIN,
        "Uncommon Tag" => Item::Uncommon_Tag,
        "Rare Tag" => Item::Rare_Tag,
        "Negative Tag" => Item::Negative_Tag,
        "Foil Tag" => Item::Foil_Tag,
        "Holographic Tag" => Item::Holographic_Tag,
        "Polychrome Tag" => Item::Polychrome_Tag,
        "Investment Tag" => Item::Investment_Tag,
        "Voucher Tag" => Item::Voucher_Tag,
        "Boss Tag" => Item::Boss_Tag,
        "Standard Tag" => Item::Standard_Tag,
        "Charm Tag" => Item::Charm_Tag,
        "Meteor Tag" => Item::Meteor_Tag,
        "Buffoon Tag" => Item::Buffoon_Tag,
        "Handy Tag" => Item::Handy_Tag,
        "Garbage Tag" => Item::Garbage_Tag,
        "Ethereal Tag" => Item::Ethereal_Tag,
        "Coupon Tag" => Item::Coupon_Tag,
        "Double Tag" => Item::Double_Tag,
        "Juggle Tag" => Item::Juggle_Tag,
        "D6 Tag" => Item::D6_Tag,
        "Top-up Tag" => Item::Top_up_Tag,
        "Speed Tag" => Item::Speed_Tag,
        "Orbital Tag" => Item::Orbital_Tag,
        "Economy Tag" => Item::Economy_Tag,
        "TAG END" => Item::TAG_END,
        "B BEGIN" => Item::B_BEGIN,
        "Small Blind" => Item::Small_Blind,
        "Big Blind" => Item::Big_Blind,
        "The Hook" => Item::The_Hook,
        "The Ox" => Item::The_Ox,
        "The House" => Item::The_House,
        "The Wall" => Item::The_Wall,
        "The Wheel" => Item::The_Wheel,
        "The Arm" => Item::The_Arm,
        "The Club" => Item::The_Club,
        "The Fish" => Item::The_Fish,
        "The Psychic" => Item::The_Psychic,
        "The Goad" => Item::The_Goad,
        "The Water" => Item::The_Water,
        "The Window" => Item::The_Window,
        "The Manacle" => Item::The_Manacle,
        "The Eye" => Item::The_Eye,
        "The Mouth" => Item::The_Mouth,
        "The Plant" => Item::The_Plant,
        "The Serpent" => Item::The_Serpent,
        "The Pillar" => Item::The_Pillar,
        "The Needle" => Item::The_Needle,
        "The Head" => Item::The_Head,
        "The Tooth" => Item::The_Tooth,
        "The Flint" => Item::The_Flint,
        "The Mark" => Item::The_Mark,
        "B F BEGIN" => Item::B_F_BEGIN,
        "Amber Acorn" => Item::Amber_Acorn,
        "Verdant Leaf" => Item::Verdant_Leaf,
        "Violet Vessel" => Item::Violet_Vessel,
        "Crimson Heart" => Item::Crimson_Heart,
        "Cerulean Bell" => Item::Cerulean_Bell,
        "B F END" => Item::B_F_END,
        "B END" => Item::B_END,
        "SUIT BEGIN" => Item::SUIT_BEGIN,
        "Hearts" => Item::Hearts,
        "Clubs" => Item::Clubs,
        "Diamonds" => Item::Diamonds,
        "Spades" => Item::Spades,
        "SUIT END" => Item::SUIT_END,
        "RANK BEGIN" => Item::RANK_BEGIN,
        "2" => Item::_2,
        "3" => Item::_3,
        "4" => Item::_4,
        "5" => Item::_5,
        "6" => Item::_6,
        "7" => Item::_7,
        "8" => Item::_8,
        "9" => Item::_9,
        "10" => Item::_10,
        "Jack" => Item::Jack,
        "Queen" => Item::Queen,
        "King" => Item::King,
        "Ace" => Item::Ace,
        "RANK END" => Item::RANK_END,
        "C BEGIN" => Item::C_BEGIN,
        "C 2" => Item::C_2,
        "C 3" => Item::C_3,
        "C 4" => Item::C_4,
        "C 5" => Item::C_5,
        "C 6" => Item::C_6,
        "C 7" => Item::C_7,
        "C 8" => Item::C_8,
        "C 9" => Item::C_9,
        "C A" => Item::C_A,
        "C J" => Item::C_J,
        "C K" => Item::C_K,
        "C Q" => Item::C_Q,
        "C T" => Item::C_T,
        "D 2" => Item::D_2,
        "D 3" => Item::D_3,
        "D 4" => Item::D_4,
        "D 5" => Item::D_5,
        "D 6" => Item::D_6,
        "D 7" => Item::D_7,
        "D 8" => Item::D_8,
        "D 9" => Item::D_9,
        "D A" => Item::D_A,
        "D J" => Item::D_J,
        "D K" => Item::D_K,
        "D Q" => Item::D_Q,
        "D T" => Item::D_T,
        "H 2" => Item::H_2,
        "H 3" => Item::H_3,
        "H 4" => Item::H_4,
        "H 5" => Item::H_5,
        "H 6" => Item::H_6,
        "H 7" => Item::H_7,
        "H 8" => Item::H_8,
        "H 9" => Item::H_9,
        "H A" => Item::H_A,
        "H J" => Item::H_J,
        "H K" => Item::H_K,
        "H Q" => Item::H_Q,
        "H T" => Item::H_T,
        "S 2" => Item::S_2,
        "S 3" => Item::S_3,
        "S 4" => Item::S_4,
        "S 5" => Item::S_5,
        "S 6" => Item::S_6,
        "S 7" => Item::S_7,
        "S 8" => Item::S_8,
        "S 9" => Item::S_9,
        "S A" => Item::S_A,
        "S J" => Item::S_J,
        "S K" => Item::S_K,
        "S Q" => Item::S_Q,
        "S T" => Item::S_T,
        "C END" => Item::C_END,
        "D BEGIN" => Item::D_BEGIN,
        "Red Deck" => Item::Red_Deck,
        "Blue Deck" => Item::Blue_Deck,
        "Yellow Deck" => Item::Yellow_Deck,
        "Green Deck" => Item::Green_Deck,
        "Black Deck" => Item::Black_Deck,
        "Magic Deck" => Item::Magic_Deck,
        "Nebula Deck" => Item::Nebula_Deck,
        "Ghost Deck" => Item::Ghost_Deck,
        "Abandoned Deck" => Item::Abandoned_Deck,
        "Checkered Deck" => Item::Checkered_Deck,
        "Zodiac Deck" => Item::Zodiac_Deck,
        "Painted Deck" => Item::Painted_Deck,
        "Anaglyph Deck" => Item::Anaglyph_Deck,
        "Plasma Deck" => Item::Plasma_Deck,
        "Erratic Deck" => Item::Erratic_Deck,
        "Challenge Deck" => Item::Challenge_Deck,
        "D END" => Item::D_END,
        "CHAL BEGIN" => Item::CHAL_BEGIN,
        "The Omelette" => Item::The_Omelette,
        "15 Minute City" => Item::_15_Minute_City,
        "Rich get Richer" => Item::Rich_get_Richer,
        "On a Knife's Edge" => Item::On_a_Knifes_Edge,
        "X-ray Vision" => Item::X_ray_Vision,
        "Mad World" => Item::Mad_World,
        "Luxury Tax" => Item::Luxury_Tax,
        "Non-Perishable" => Item::Non_Perishable,
        "Medusa" => Item::Medusa,
        "Double or Nothing" => Item::Double_or_Nothing,
        "Typecast" => Item::Typecast,
        "Inflation" => Item::Inflation,
        "Bram Poker" => Item::Bram_Poker,
        "Fragile" => Item::Fragile,
        "Monolith" => Item::Monolith,
        "Blast Off" => Item::Blast_Off,
        "Five-Card Draw" => Item::Five_Card_Draw,
        "Golden Needle" => Item::Golden_Needle,
        "Cruelty" => Item::Cruelty,
        "Jokerless" => Item::Jokerless,
        "CHAL END" => Item::CHAL_END,
        "STAKE BEGIN" => Item::STAKE_BEGIN,
        "White Stake" => Item::White_Stake,
        "Red Stake" => Item::Red_Stake,
        "Green Stake" => Item::Green_Stake,
        "Black Stake" => Item::Black_Stake,
        "Blue Stake" => Item::Blue_Stake,
        "Purple Stake" => Item::Purple_Stake,
        "Orange Stake" => Item::Orange_Stake,
        "Gold Stake" => Item::Gold_Stake,
        "STAKE END" => Item::STAKE_END,
        "RARITY BEGIN" => Item::RARITY_BEGIN,
        "Common" => Item::Common,
        "Uncommon" => Item::Uncommon,
        "Rare" => Item::Rare,
        "Legendary" => Item::Legendary,
        "RARITY END" => Item::RARITY_END,
        "TYPE BEGIN" => Item::TYPE_BEGIN,
        "T Joker" => Item::T_Joker,
        "T Tarot" => Item::T_Tarot,
        "T Planet" => Item::T_Planet,
        "T Spectral" => Item::T_Spectral,
        "T Playing Card" => Item::T_Playing_Card,
        "TYPE END" => Item::TYPE_END,
        _ => Item::RETRY,
    }
}

pub fn is_joker_item(item: Item) -> bool {
    item > Item::J_BEGIN
        && item < Item::J_END
        && !matches!(
            item,
            Item::J_C_BEGIN
                | Item::J_C_END
                | Item::J_U_BEGIN
                | Item::J_U_END
                | Item::J_R_BEGIN
                | Item::J_R_END
                | Item::J_L_BEGIN
                | Item::J_L_END
        )
}
